### ISSUE TITLE
Enable ESM & CI/CD deploy to NPM by GitHub Actions

### ISSUE THREAD

**Issue by huan** [wechaty/plugin-chatopera#9]
The ESM PR is ready to be merged:

- #8 

After it can pass the CI and be merged, then we can enable publish to NPM by adding an `NPM_TOKEN` to secret in repo settings.

**Comment by huan** [comment]
We have merged the ESM support with great help from @mukaiu 

What we need to do next step is to rename the default branch name from `developer` to `main` so that we can enable GitHub Actions. 

See: https://github.com/wechaty/plugin-chatopera/blob/develop/.github/workflows/npm.yml

**Comment by huan** [comment]
ping @mukaiu @hailiang-wang 

Could we add `NPM_TOKEN` to the repo secret so that we can enable CI/CD for publishing to NPM automatically?

And it would be great if you can also add my NPM account (zixia) to maintainer of the npm module `wechaty-chatopera`, thank you very much!

**Comment by mukaiu** [comment]
npm maintainer has been added.

**Comment by huan** [comment]
- [x] `NPM_TOKEN` added
- [x] maintainer added
- [x] ESM enabled

Close this issue
